
# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: monah
# "service" is the name of this project. This will also be added to your AWS resource names.
service: my-serverless-project

useDotenv: true

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  environment:
    DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
      Resource:
        - arn:aws:dynamodb:us-east-1:448049791700:table/http-crud-tutorial-items

package:
  individually: true

functions: ${file(modules/item/routes.yml)}

resources:
  Resources:
    HttpCrudTutorialItems:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: http-crud-tutorial-items
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: item_id
            AttributeType: S
        KeySchema:
          - AttributeName: item_id
            KeyType: HASH
